version: '3'

services:
  mysql-database:
    image: mysql:latest
    container_name: my-mysql-container
    env_file: ./.env
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: nome_do_banco
      MYSQL_USER: usuario_do_banco
      MYSQL_PASSWORD: senha_do_usuario
    ports:
      - "3306:3306"
    networks:
      - my-network
    volumes:
      - db:/var/lib/mysql

  dental-appointment-manager:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dental-appointment-manager-api
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: usuario_do_banco
      DB_PASSWORD: senha_do_usuario
      DB_DATABASE: nome_do_banco
    ports:
      - "3000:3000"
    depends_on:
      - mysql-database
    networks:
      - my-network

networks:
  dental-appointment-manager-network:
    driver: bridge
